### PR TITLE
accept-transfer: fix infinite render leading to roller request spam

### LINKED ISSUE #709: L1 tx confirmed but progress bar still says "sending..."
This was when logged in with Metamask. The progress bar stayed completely empty while it was awaiting confirmation (presumably due to mm not giving us the data we want until confirmation), but once the tx confirmed, the progress bar went to ~90%, and just... stayed there:

image

No relevant output in the web console.

Update: I can reproduce this consistently for the "accept transfer" flow, but not for other transactions.

### PR DESCRIPTION
**Pull request by pkova**
I recently decided to accept some stars. It was not a great experience, hence this PR.

The root of the problem is that Bridge is polling the roller every second, which together with some bugs relating to reference equality results in a DDOS-esque number of requests to the roller after a the transaction to accept the point completes.

Fixes #709, #965

### CODE REVIEW

File: src/store/pointCache.js [hunk 1]
```diff
@@ -8,7 +9,7 @@ export function PointCacheProvider({ children }) {
   const cache = usePointStore();
 
   return (
-    <PointCacheContext.Provider value={cache}>
+    <PointCacheContext.Provider value={useDeepEqualReference(cache)}>
```
Comment (pkova) [inline src/store/pointCache.js:12]: Using reference equality here causes the `AcceptTransfer` component to rerender for no reason every second.

File: src/views/AcceptTransfer.tsx [hunk 2]
```diff
@@ -53,7 +53,7 @@ function useAcceptTransfer() {
     ),
     useCallback(
       () => Promise.all([syncExtras(_point), syncControlledPoints()]),
-      [_point, syncControlledPoints, syncExtras]
+      [_point]
```
Comment (pkova) [inline src/views/AcceptTransfer.tsx:56]: Having `syncControlledPoints` and `syncExtras` as dependencies causes the crazy amount of HTTP requests, again because of reference equality checks.

File: src/lib/useRoller.ts [hunk 3]
```diff
@@ -210,30 +210,33 @@ export default function useRoller() {
...
+
       if (l1Txn) storePendingL1Txn(l1Txn);
 
       let interval: any;
       const check = async () => {
-        const updatedPoint = await initPoint(point);
         const changedField = !points[point]
           ? 'newPoint'
-          : updatedPoint.getChangedField(points[point], field);
+          : point.getChangedField(points[point], field);
```
Comment (pkova) [inline src/lib/useRoller.ts:224]: I also decided to change the `checkForUpdates` api somewhat, since I noticed that after fixing the ddos-bug this interval would keep polling every ten seconds forever, since the point transfer was already present after calling `initPoint`. Callsites can still use the old behavior with `pointValue`, but most of them have access to a proper `Point` object.

**Comment by tomholford** [comment]
@pkova Thank you so much for your contribution. Legendary!

Pulled the branch to try it out locally, but ran into this issue:

image

If this is more than a quick Typescript fix, I can take a look at this later this week.

**Comment by pkova** [comment]
Back in my day Bridge was Javascript!

Fixed the typescript errors, let me know if it works now.

**Comment by pkova** [comment]
I noticed that `tsc` still complains, but it's about files that are unchanged from my stuff.

**Review by tomholford — APPROVED** [review]
pulled and tried it out locally, LGTM. Thanks @pkova
