### PR TITLE
Fix rekey date issue, add contract address

### LINKED ISSUE #185: getPastEvents undefined
https://github.com/urbit/bridge/blob/mino/src/store/lib/useRekeyDateStore.js#L34

```
useRekeyDateStore.js:34 Uncaught (in promise) TypeError: azimuth_js__WEBPACK_IMPORTED_MODULE_4__.azimuth.getPastEvents is not a function
    at useRekeyDateStore.js:34
    at usePointStore.js:22
    at usePointStore.js:31
    at Array.map (<anonymous>)
    at useSyncPoints.js:15
    at commitHookEffectList (react-dom.development.js:18055)
    at commitPassiveHookEffects (react-dom.development.js:18082)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:198)
    at invokeGuardedCallback (react-dom.development.js:252)
    at commitPassiveEffects (react-dom.development.js:19708)
    at wrapped (scheduler-tracing.development.js:177)
    at flushPassiveEffects (react-dom.development.js:19761)
    at renderRoot (react-dom.development.js:20334)
    at performWorkOnRoot (react-dom.development.js:21359)
    at performWork (react-dom.development.js:21269)
    at performSyncWork (react-dom.development.js:21243)
    at interactiveUpdates$1 (react-dom.development.js:21528)
    at interactiveUpdates (react-dom.development.js:2270)
    at dispatchInteractiveEvent (react-dom.development.js:5087)
(anonymous) @ useRekeyDateStore.js:34
(anonymous) @ usePointStore.js:22
(anonymous) @ usePointStore.js:31
(anonymous) @ useSyncPoints.js:15
commitHookEffectList @ react-dom.development.js:18055
commitPassiveHookEffects @ react-dom.development.js:18082
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:198
invokeGuardedCallback @ react-dom.development.js:252
commitPassiveEffects @ react-dom.development.js:19708
wrapped @ scheduler-tracing.development.js:177
flushPassiveEffects @ react-dom.development.js:19761
renderRoot @ react-dom.development.js:20334
performWorkOnRoot @ react-dom.development.js:21359
performWork @ react-dom.development.js:21269
performSyncWork @ react-dom.development.js:21243
interactiveUpdates$1 @ react-dom.development.js:21528
interactiveUpdates @ react-dom.development.js:2270
dispatchInteractiveEvent @ react-dom.development.js:5087
```

### PR DESCRIPTION
**Pull request by Fang-**
Straightforward one here!

closes #185

### CODE REVIEW

File: src/store/lib/useInvitesStore.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ export default function useInvitesStore() {
       );
 
       const sentInvites = invitedPoints.length;
-      const acceptedInvites = activity.filter(i => i.active).length;
+      const acceptedInvites = activity.filter(i => i).length;
```
Comment (shrugs) [inline src/store/lib/useInvitesStore.js]: use `!!i` to coerce into a boolean

File: src/store/lib/useRekeyDateStore.js [hunk 2]
```diff
@@ -28,10 +28,14 @@ export default function useRekeyDateStore() {
...
       }
+      const _contracts = contracts.getOrElse(null);
+      if (!_contracts) {
+        return;
+      }
 
       //TODO tighter search?
       //TODO maybe move into azimuth-js?
-      const logs = await azimuth.azimuth.getPastEvents('ChangedKeys', {
+      const logs = await _contracts.azimuth.getPastEvents('ChangedKeys', {
```
Comment (shrugs) [inline src/store/lib/useRekeyDateStore.js]: ah, nice 👍

**Comment by shrugs** [comment]
closes #185
